name: Portfolio Backend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DB_USER: test_user
  DB_PASS: test_pass
  DB_NAME: test_portfolio
  DB_HOST: localhost

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Wait for MySQL to start
        run: |
          sudo systemctl start mysql
          sleep 10

      - name: Create user
        run: |
          mysql -u root -proot -e "CREATE USER '${{ env.DB_USER }}'@'${{env.DB_HOST}}' IDENTIFIED BY '${{ env.DB_PASS }}';"
          mysql -u root -proot -e "GRANT ALL PRIVILEGES ON ${{ env.DB_NAME }}.* TO '${{ env.DB_USER }}'@'${{env.DB_HOST}}';"
          mysql -u root -proot -e "FLUSH PRIVILEGES;"

      - name: Create MySQL database and tables
        run: |
          mysql -u root -proot -e "CREATE DATABASE IF NOT EXISTS ${{ env.DB_NAME }};"
          mysql -h ${{ env.DB_HOST }} -u ${{ env.DB_USER }} -p${{ env.DB_PASS }} ${{ env.DB_NAME }} < create_tables.sql
          mysql -u root -proot -e "SHOW DATABASES;"
          mysql -u root -proot -e "USE ${{ env.DB_NAME }}; SHOW TABLES;"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Lint with black
        run: |
          black --check .
      - name: Test with pytest
        run: |
          export DB_USER="root"
          export DB_PASS="root"
          export DB_NAME="${{ env.DB_NAME }}"
          export DB_HOST="${{ env.DB_HOST }}"
          pytest -s
