name: Portfolio Backend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DB_USER: root
  DB_PASS:
  DB_NAME: test_portfolio
  DB_HOST: localhost

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASS }}
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASS }}
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Wait for MySQL to start
        run: |
          sudo systemctl start mysql
          sleep 10
          systemctl status mysql.service

      - name: Create MySQL database and tables
        run: |
          mysql -h ${{ env.DB_HOST }} -u ${{ env.DB_USER }} -p${{ env.DB_PASS }} -e "CREATE DATABASE IF NOT EXISTS ${{ env.DB_NAME }};"
          mysql -h ${{ env.DB_HOST }} -u ${{ env.DB_USER }} -p${{ env.DB_PASS }} ${{ env.DB_NAME }} < path/to/create_tables.sql

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Lint with black
        run: |
          black --check .
          - name: Test with pytest
          run: |
            export DB_USER="${{ env.DB_USER }}"
            export DB_PASS="${{ env.DB_PASS }}"
            export DB_NAME="${{ env.DB_NAME }}"
            export DB_HOST="${{ env.DB_HOST }}"
            pytest -s
